
-- Fix conveniences table ID column to be auto-incrementing identity
-- First, find max ID to restart sequence correctly
DO $$
DECLARE
    max_id bigint;
BEGIN
    SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM conveniences;
    
    -- Check if it is already an identity column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'conveniences' AND column_name = 'id' AND is_identity = 'YES'
    ) THEN
        -- If not identity, make it one. 
        -- If it's a simple integer/bigint without default:
        EXECUTE 'ALTER TABLE conveniences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH ' || max_id || ')';
    ELSE
        -- If it is identity but maybe out of sync?
        -- Restart sequence just in case
        EXECUTE 'ALTER TABLE conveniences ALTER COLUMN id RESTART WITH ' || max_id;
    END IF;
END $$;
